const fileInput=document.querySelector('#file-input'),dropzone=document.querySelector('#dropzone'),previewWrap=document.querySelector('#preview-wrap'),imagePreview=document.querySelector('#image-preview'),fileName=document.querySelector('#file-name'),removeButton=document.querySelector('#remove-button'),extractButton=document.querySelector('#extract-button'),copyButton=document.querySelector('#copy-button'),pasteButton=document.querySelector('#paste-button'),resultText=document.querySelector('#result-text'),characterCount=document.querySelector('#character-count'),statusPanel=document.querySelector('#status-panel'),statusText=document.querySelector('#status-text'),progressBar=document.querySelector('#progress-bar'),progressValue=document.querySelector('#progress-value'),errorMessage=document.querySelector('#error-message');
let selectedFile=null,previewUrl=null;
function showError(message){errorMessage.textContent=message;errorMessage.classList.remove('is-hidden')}function clearError(){errorMessage.textContent='';errorMessage.classList.add('is-hidden')}
function setProgress(progress,message){const percent=Math.max(0,Math.min(100,Math.round(progress*100)));progressBar.style.width=`${percent}%`;progressValue.textContent=`${percent}%`;if(message)statusText.textContent=message}
function handleFile(file){clearError();if(!file)return;const validTypes=['image/jpeg','image/png','image/webp'];if(!validTypes.includes(file.type)){showError('Unsupported file format. Please use JPG, PNG, or WEBP.');return}if(file.size>10*1024*1024){showError('This image is too large. The maximum file size is 10 MB.');return}selectedFile=file;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);imagePreview.src=previewUrl;fileName.textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;previewWrap.classList.remove('is-hidden');extractButton.disabled=false;resultText.value='';copyButton.disabled=true;updateCharacterCount()}
function resetApp(){selectedFile=null;fileInput.value='';if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=null;imagePreview.removeAttribute('src');previewWrap.classList.add('is-hidden');statusPanel.classList.add('is-hidden');extractButton.disabled=true;extractButton.querySelector('span').textContent='Extract text';clearError()}
async function extractText(){if(!selectedFile||typeof Tesseract==='undefined')return;clearError();extractButton.disabled=true;extractButton.querySelector('span').textContent='Processing...';statusPanel.classList.remove('is-hidden');setProgress(0,'Preparing OCR...');try{const result=await Tesseract.recognize(selectedFile,'ind+eng',{logger:({status,progress})=>{const labels={'loading tesseract core':'Loading OCR engine...','initializing tesseract':'Initializing OCR...','loading language traineddata':'Loading English + Indonesian...','recognizing text':'Recognizing text...'};setProgress(progress||0,labels[status]||status||'Processing...')}});resultText.value=result.data.text.trim();updateCharacterCount();copyButton.disabled=!resultText.value;setProgress(1,resultText.value?'Done.':'No text detected in this image.')}catch(error){console.error(error);showError('OCR failed. Check your internet connection and try again.');setProgress(0,'Could not process image.')}finally{extractButton.disabled=false;extractButton.querySelector('span').textContent='Extract text'}}
async function copyText(){if(!resultText.value)return;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(resultText.value)}else{const helper=document.createElement('textarea');helper.value=resultText.value;helper.style.position='fixed';helper.style.opacity='0';document.body.appendChild(helper);helper.focus();helper.select();document.execCommand('copy');helper.remove()}const original=copyButton.textContent;copyButton.textContent='Copied!';setTimeout(()=>{copyButton.textContent=original},2000)}catch(error){showError('Automatic copy failed. Please copy the text manually.')}}
async function pasteText(){try{if(!navigator.clipboard?.readText){showError('Clipboard paste is not supported by this browser. Use Ctrl+V instead.');return}const clipboardText=await navigator.clipboard.readText();if(!clipboardText){showError('Your clipboard does not contain text.');return}resultText.value=clipboardText;updateCharacterCount();copyButton.disabled=false;resultText.focus()}catch(error){showError('Clipboard permission was denied. Click inside the text box and press Ctrl+V instead.')}}function updateCharacterCount(){const count=resultText.value.length;characterCount.textContent=`${count.toLocaleString()} ${count===1?'character':'characters'}`}
fileInput.addEventListener('change',event=>handleFile(event.target.files[0]));removeButton.addEventListener('click',resetApp);extractButton.addEventListener('click',extractText);copyButton.addEventListener('click',copyText);pasteButton.addEventListener('click',pasteText);resultText.addEventListener('input',()=>{updateCharacterCount();copyButton.disabled=!resultText.value});dropzone.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();fileInput.click()}});['dragenter','dragover'].forEach(name=>dropzone.addEventListener(name,event=>{event.preventDefault();dropzone.classList.add('is-dragging')}));['dragleave','drop'].forEach(name=>dropzone.addEventListener(name,event=>{event.preventDefault();dropzone.classList.remove('is-dragging')}));dropzone.addEventListener('drop',event=>handleFile(event.dataTransfer.files[0]));
document.querySelectorAll('.legal-dialog').forEach(dialog=>{dialog.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()})});document.querySelectorAll('a[href="#privacy"],a[href="#terms"]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();document.querySelector(link.getAttribute('href')).showModal()}));
